baseURL: "https://circleofgrowth.net"
languageCode: "en-us"
title: "Circle of Growth"
theme: profile-ng

Paginate: 3
#disqusShortname: gurusabarish
#googleAnalytics: G-N25TY2TYNR 

markup:
  goldmark:
    renderer:
      unsafe: true

enableEmoji: True

params:
  customCSS: true
  color:
      textColor: "#161616"
      #secondaryTextColor: "#311D3F"
      #backgroundColor: "#34BE82" 
      primaryColor: "#618812"
      secondaryColor: "#81b026"
  
  title: "Circle of Growth"
  description: Leadership coaching. 
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/favicon.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: True
    defaultTheme: "light" # dark
  
  # Site home
  hero:
    enable: true
    title: "Ramez Hanna"
    subtitle: |-
      Let's grow together
    content: |-
      Empowering you to overcome your challenges  
      Helping leaders become their better selves.  
      Unblock yourself and reach your potential       
    image: "/images/hero.png"
    button:
      enable: true
      name: "Schedule a call"
      url: "https://cal.com/ramezhanna/short"
      download: false

  sections:
    - Name: "Aboutyou"
      enable: True
      title: "About you"
      imnage:

    - Name: "Coaching"
      enable: true
      title: "Coaching"
      image: "/images/butterfly-transform.png"
      content: |-
        #### What is coaching?
        Coaching is a form of development in which an experienced person, called a coach, supports a learner, called a coachee, in achieving a specific personal or professional goal by providing training and guidance.  
        In simple terms, coaching is an opportunity for the coachee to take the time to work on themselves with the help of a coach.  
        The coach helps the coachee in gaining clarity on their goals. Be mindful of their current ways. Paint a picture of the destination and support them in getting there.

        <img src="/images/coaching-diag.png" width="100%">

        #### How does it go?
        A coaching program has a start and an end.
        * It starts with the coachee having a topic to work on that is important to them and their development.
        * A discovery session, in which the coach and the coachee learn a little about each other, break the ice. They will also start to discover the topic. The purpose is for both to get clarity on the topic.
        * In the next session, the coach will propose a coaching program that is customized to the coachee that runs over several sessions (4-6 months). They will discuss and refine it together.
          The program will have clear goals and exercises to help the coachee achieve them.
        * Finally, there is a closing session to review and celebrate the change.  
        
        Yet the journey doesn’t stop there, the coach merely helps the coachee get on the path to achieving their goals.  
        After the program is over, the work goes on and the coachee continues on their journey of growth without the coach.  
        **Ready to step in? Let’s talk. <a href="#" data-bs-toggle="modal" data-bs-target="#bookme">Book a free call</a> with me.**

        #### Who is it for?
        Coaching can be helpful for individuals and teams who want to achieve their goals and improve their performance.
        It can be useful for people looking to make changes in their personal or professional lives, and who want support and guidance in achieving their goals.   
        Coaching can be useful for people looking to develop specific skills or knowledge, such as leadership or communication skills. It can also be helpful for people who are going through significant life transitions, such as a career change or a move to a new city.  
        
        Overall, coaching can be beneficial for anyone who wants to achieve personal and professional growth and fulfillment, and who is willing to put in the effort and commitment to make it happen.  
        **Not sure if that is for you? <a href="#" data-bs-toggle="modal" data-bs-target="#bookme">Book a free intro call</a> and we can walk through options.**

        #### What are the requirements?
        The only requirement is to have a topic.  
        A topic can be anything that you want to achieve or improve. It could even be about finding a goal.  
        **The best way to figure out if you are ready is to do it. <a href="#" data-bs-toggle="modal" data-bs-target="#bookme">Book a free call</a> with me and let's talk.**
    
    - Name: "Aboutme"
      enable: true
      title: "About Me"
      image: "/images/ICC-IAC-style1.png"
      content: |-
        I am Ramez Hanna, someone like you who is successful in his career. Like you I have challenges.
        I learned the hardway that real change doesn't happen through techniques or self help books
        Real change, the kind that unblocks us and changes us personally and professionally happens through a change in mindset.
        It happens through a lot of self work

        I was fortunate to have been coached. Which has been a turning point in my life.
        Since then I wanted to be able to help people like I was helped.
        Integral Coaching changed my mindset, gave me the knowledge and the tools to create change.

        Today I am here to be available for a bigger audience. <a href="#" class="link-dark" data-bs-toggle="modal" data-bs-target="#bookme">Book a free call</a>, let's talk.
    - Name: "Contact"
      enable: true
      title: "Contact"
      content: |-
        For any questions or inquiries feel free to message me over [LinkedIn](https://www.linkedin.com/in/ramezhanna/) or email me at rhanna at circleofgrowth dot net

  footer:
    recentPosts: false
    socialNetworks:
      linkedin: https://www.linkedin.com/in/ramezhanna/
